name: nsca_daily
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  provider: ^6.1.4
  http: ^1.3.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  percent_indicator: ^4.2.5
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  intl: ^0.20.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  connectivity_plus: ^6.1.4
  html_unescape: ^2.0.0
  universal_html: ^2.2.4
  pod_player: ^0.2.2
  webview_flutter: ^4.11.0
  logging: ^1.3.0
  json_annotation: ^4.9.0
  vimeo_embed_player: ^1.0.2
  share_plus: ^11.0.0
  youtube_player_flutter: ^9.1.1
  video_player: ^2.9.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash.png
    - assets/images/login_forget.png
    - assets/images/do_login.png
    - assets/images/long_arrow_right.png
    - assets/images/loading_animated.gif
    - assets/images/play.png
    - assets/images/no_connection.png
  fonts:
    - family: google_sans
      fonts:
        - asset: assets/fonts/google_sans_regular.ttf
        - asset: assets/fonts/google_sans_bold.ttf
          weight: 700
  
